<a href="https://colab.research.google.com/github/Gamez0/TensorFlow2.0/blob/main/tf2_06_1_softmax_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Softmax function 은 여러개의(N개) class를 예측해야 할 때 유용하다.
ex) 성적: A B C F
XW = Y -> [2.0,1.0,0.1] -> SoftMax -> [0.7, 0.2, 0.1]
SoftMax를 거치면 확률로 나온다. 나온 값들의 합은 1이다.

one hot encoding 을 통해서 [1.0, 0.0, 0.0]으로 나올 수 있다.

Cost function: cross entropy

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

In [4]:
nb_classes = 3

In [5]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))

In [7]:
tf.model.add(tf.keras.layers.Activation('softmax'))

In [8]:
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation_1 (Activation)    (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = tf.model.fit(x_data,y_data, epochs=2000)

In [10]:
print('--------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1,11,7,9]]))
print(a, tf.keras.backend.eval(tf.argmax(a,axis=1)))

--------------
[[4.2066765e-03 9.9578357e-01 9.7486836e-06]] [1]


In [13]:
print('--------------')
b = tf.model.predict(np.array([[1,3,4,3]]))
print(b,tf.keras.backend.eval(tf.argmax(b,axis=1)))

--------------
[[0.8719065  0.11527461 0.01281898]] [0]


In [14]:
print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1,1,0,1]]))
c_onehot = tf.model.predict_classes(np.array([[1,1,0,1]]))
print(c, c_onehot)

--------------
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[1.2407665e-08 3.4634044e-04 9.9965370e-01]] [2]
